CREATE OR REPLACE PROCEDURE UpdateEmployeeBonus(
    D IN EMPLOYEES.DEPT%TYPE, 
    BONUS_RATE FLOAT
)
IS
NEW_SALARY EMPLOYEES.SALARY%TYPE;
BEGIN
    UPDATE EMPLOYEES 
    SET SALARY=SALARY*(1+(BONUS_RATE/100)) 
    WHERE DEPT=D;
    DBMS_OUTPUT.PUT_LINE('UPDATED SALARY OF DEPARTMENT ' || D || ' WITH BONUS RATE OF ' || BONUS_RATE || '%');
END;

BEGIN 
    UpdateEmployeeBonus('IT', 1.2);
END;