CREATE OR REPLACE PROCEDURE ProcessMonthlyInterest 
IS
IRATE FLOAT := 1;
NAME CUSTOMERS.NAME%TYPE;
BALANCE CUSTOMERS.BALANCE%TYPE;
NEWBALANCE CUSTOMERS.BALANCE%TYPE;
CURSOR CC IS SELECT NAME, BALANCE FROM CUSTOMERS FOR UPDATE;
BEGIN
    OPEN CC;
    LOOP
        FETCH CC INTO NAME, BALANCE;
        EXIT WHEN CC%NOTFOUND;
        NEWBALANCE:=BALANCE*(1+0.01);
        UPDATE CUSTOMERS
        SET BALANCE=NEWBALANCE
        WHERE CURRENT OF CC;
        DBMS_OUTPUT.PUT_LINE('New balance for ' || NAME || ' is ' || NEWBALANCE);
    END LOOP;
    CLOSE CC;
END;

BEGIN
    ProcessMonthlyInterest();
END;