DECLARE
    ID CUSTOMERS.ID%TYPE;
    NAME CUSTOMERS.NAME%TYPE;
    BALANCE CUSTOMERS.BALANCE%TYPE;
    FLAG CUSTOMERS.ISVIP%TYPE;
    CURSOR CC IS 
    SELECT ID, NAME, BALANCE FROM CUSTOMERS FOR UPDATE;
BEGIN
    OPEN CC;
    LOOP
        FETCH CC INTO ID, NAME, BALANCE;
        EXIT WHEN CC%NOTFOUND;
        IF BALANCE>10000 THEN
            FLAG:='TRUE';
            DBMS_OUTPUT.PUT_LINE(NAME || ' IS VIP' );
        ELSE 
            FLAG:='FALSE';
            DBMS_OUTPUT.PUT_LINE(NAME || ' IS NOT VIP' );
        END IF;
        UPDATE CUSTOMERS
        SET ISVIP=FLAG
        WHERE CURRENT OF CC;
    END LOOP;
    CLOSE CC;
END;
