DECLARE
    ID CUSTOMERS.ID%TYPE;
    NAME CUSTOMERS.NAME%TYPE;
    DUEDATE CUSTOMERS.DUEDATE%TYPE;
    CURSOR CC IS 
    SELECT ID, NAME, DUEDATE FROM CUSTOMERS FOR UPDATE;
BEGIN
    OPEN CC;
    LOOP
        FETCH CC INTO ID, NAME, DUEDATE;
        EXIT WHEN CC%NOTFOUND;
        IF DUEDATE<=SYSDATE+30 THEN
            DBMS_OUTPUT.PUT_LINE('Hello, ' || NAME || 'Your loan is due on ' || DUEDATE);
        END IF;
    END LOOP;
    CLOSE CC;
END;
